name: mbanglabatenteb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.4.0
  shared_preferences: ^2.5.5
  http: ^1.2.1
  flutter_tts: ^4.2.5
  audioplayers: ^6.8.1
  url_launcher: ^6.3.0
  mobile_scanner: ^7.4.0
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
