class QuestionDatabase {
  // Glossary map for auto-generating vocabulary help and multi-word phrase lookups
  static const Map<String, String> globalGlossary = {
    // Multi-word phrases (Longer compound traffic expressions)
    'un tratto di strada': 'রাস্তার একটি অংশ',
    'tratto di strada': 'রাস্তার অংশ',
    'strada deformata': 'অসমতল / খাঁজকাটা রাস্তা',
    'pavimentazione irregolare': 'অমসৃণ / ভাঙাচোরা রাস্তা',
    'segnale di pericolo': 'বিপদ সংকেত',
    'segnale raffigurato': 'প্রদর্শিত সংকেতটি / রোড সাইনটি',
    'limite massimo di velocità': 'সর্বোচ্চ গতিসীমা',
    'limite di velocità': 'গতিসীমা',
    'senso unico di circolazione': 'একমুখী যানবাহন চলাচল',
    'senso unico': 'একমুখী',
    'doppio senso di circolazione': 'উভয়মুখী যানবাহন চলাচল',
    'doppio senso': 'উভয়মুখী',
    'passaggio a livello': 'রেলওয়ে লেভেল ক্রসিং',
    'dare precedenza': 'অগ্রাধিকার প্রদান করা',
    'diritto di precedenza': 'অগ্রাধিকার পাওয়ার অধিকার',
    'banchina cedevole': 'ধসপ্রবণ কিনারা',
    'strada sdrucciolevole': 'পিচ্ছিল রাস্তা',
    'caduta massi': 'পাথর খসে পড়ার সম্ভাবনা',
    'isola di traffico': 'ট্রাফিক আইল্যান্ড',
    'attraversamento pedonale': 'জেব্রা ক্রসিং / পথচারী পারাপার',
    'attraversamento ciclabile': 'সাইকেল পারাপার',
    'pista ciclabile': 'সাইকেল লেন',
    'zona a traffico limitato': 'সীমিত যানবাহন চলাচলের এলাকা (ZTL)',
    'area pedonale': 'পথচারী এলাকা',
    'strada extraurbana principale': 'প্রধান উপশহরীয় হাইওয়ে',
    'strada extraurbana secondaria': 'দ্বিতীয় শ্রেণির উপশহরীয় হাইওয়ে',
    'strada urbana': 'শহরের ভেতরের রাস্তা',
    'corsia di emergenza': 'জরুরি লেন / ইমার্জেন্সি লেন',
    'corsia di marcia': 'স্বাভাবিক চলার লেন',
    'corsia di sorpasso': 'ওভারটেকিং লেন',
    'corsia di accelerazione': 'গতি বাড়ানোর লেন (প্রবেশ লেন)',
    'corsia di decelerazione': 'গতি কমানোর লেন (বাহির লেন)',
    'distanza di sicurezza': 'নিরাপদ দূরত্ব',
    'spazio di frenata': 'ব্রেক করার পর থামার দূরত্ব',
    'spazio di arresto': 'সম্পূর্ণ থামার মোট দূরত্ব',
    'tempo di reazione': 'প্রতিক্রিয়া সময়',
    'luci di posizione': 'পজিশন লাইট',
    'luci anabbaglianti': 'লো-বিম লাইট',
    'luci abbaglianti': 'হাই-বিম লাইট',
    'segnale luminoso': 'আলোক সংকেত / সিগন্যাল লাইট',
    'strisce longitudinali': 'লম্বালম্বি রোড লাইন',
    'strisce trasversali': 'আড়াআড়ি রোড লাইন',
    'strisce pedonali': 'জেব্রা ক্রসিং দাগ',
    'in caso di nebbia': 'কুয়াশার ক্ষেত্রে',
    'in caso di pioggia': 'বৃষ্টির ক্ষেত্রে',
    'in caso di neve': 'তুষারপাতের ক্ষেত্রে',

    // Single words
    'strada': 'রাস্তা / রোড',
    'carreggiata': 'মূল রাস্তা / ক্যারেজওয়ে',
    'corsia': 'লেন',
    'banchina': 'রাস্তার কিনারা / ব্যাংকিনা',
    'marciapiede': 'ফুটপাথ',
    'pedoni': 'পথচারী',
    'veicolo': 'যানবাহন / গাড়ি',
    'veicoli': 'যানবাহনগুলো / গাড়িগুলো',
    'conducente': 'চালক / ড্রাইভার',
    'velocità': 'গতি / স্পিড',
    'sosta': 'পার্কিং করা',
    'fermata': 'ক্ষণিকের থামা / স্টপ',
    'sorpasso': 'ওভারটেক করা',
    'vietato': 'নিষেধ / বেআইনি',
    'consentito': 'অনুমোদিত / বৈধ',
    'obbligo': 'বাধ্যতামূলক',
    'pericolo': 'বিপদ',
    'limite': 'সীমা / লিমিট',
    'sicurezza': 'নিরাপত্তা',
    'distanza': 'দূরত্ব',
    'incrocio': 'মোড় / চৌরাস্তা',
    'precedenza': 'অগ্রাধিকার / আগে যাওয়ার সুযোগ',
    'destra': 'ডানদিক',
    'sinistra': 'বামদিক',
    'freni': 'ব্রেকসমূহ',
    'pneumatici': 'টায়ারসমূহ',
    'motore': 'ইঞ্জিন',
    'luci': 'লাইটসমূহ',
    'nebbia': 'কুয়াশা',
    'ghiaccio': 'বরফ / তুষারপাত',
    'pioggia': 'বৃষ্টি',
    'autostrada': 'হাইওয়ে / এক্সপ্রেসওয়ে',
    'passaggio': 'ক্রসিং / পথ',
    'livello': 'লেভেল',
    'segnali': 'সংকেতসমূহ',
    'segnaletica': 'রোড সাইন / চিহ্ন',
    'continua': 'অবিচ্ছিন্ন / টানা',
    'discontinua': 'বিচ্ছিন্ন / ভাঙা',
    'doppio': 'দ্বিগুণ / উভয়',
    'senso': 'দিক / অভিমুখ',
    'unico': 'একমুখী',
    'arrestarsi': 'থামা',
    'guidare': 'ড্রাইভ করা / চালানো',
    'patente': 'ড্রriving লাইসেন্স',
    'cintura': 'বেল্ট / সিটবেল্ট',
    'casco': 'হেলমেট',
    'animali': 'পশু / জানোয়ার',
    'tenere': 'রাখা / বজায় রাখা',
    'vicino': 'কাছে / নিকটে',
    'margine': 'প্রান্ত / কিনারা',
    'destro': 'ডানদিক',
    'sinistro': 'বামদিক',
    'raffigurato': 'প্রদর্শিত / চিত্রে দেখানো',
    'preannuncia': 'পূর্বে সতর্ক করে / পূর্বাভাস দেয়',
  };

  static void initialize() {}
}
