import 'mcq_question.dart';

class QuestionDatabase {
  // Glossary map for auto-generating vocabulary help and multi-word phrase lookups
  static const Map<String, String> globalGlossary = {
    // Multi-word phrases (Longer compound traffic expressions)
    'un tratto di strada': 'রাস্তার একটি অংশ',
    'tratto di strada': 'রাস্তার অংশ',
    'strada deformata': 'অসমতল / খাঁজকাটা রাস্তা',
    'pavimentazione irregolare': 'অমসৃণ / ভাঙাচোরা রাস্তা',
    'segnale di pericolo': 'বিপদ সংকেত',
    'segnale raffigurato': 'প্রদর্শিত সংকেতটি / রোড সাইনটি',
    'limite massimo di velocità': 'সর্বোচ্চ গতিসীমা',
    'limite di velocità': 'গতিসীমা',
    'senso unico di circolazione': 'একমুখী যানবাহন চলাচল',
    'senso unico': 'একমুখী',
    'doppio senso di circolazione': 'উভয়মুখী যানবাহন চলাচল',
    'doppio senso': 'উভয়মুখী',
    'passaggio a livello': 'রেলওয়ে লেভেল ক্রসিং',
    'dare precedenza': 'অগ্রাধিকার প্রদান করা',
    'diritto di precedenza': 'অগ্রাধিকার পাওয়ার অধিকার',
    'banchina cedevole': 'ধসপ্রবণ কিনারা',
    'strada sdrucciolevole': 'পিচ্ছিল রাস্তা',
    'caduta massi': 'পাথর খসে পড়ার সম্ভাবনা',
    'isola di traffico': 'ট্রাফিক আইল্যান্ড',
    'attraversamento pedonale': 'জেব্রা ক্রসিং / পথচারী পারাপার',
    'attraversamento ciclabile': 'সাইকেল পারাপার',
    'pista ciclabile': 'সাইকেল লেন',
    'zona a traffico limitato': 'সীমিত যানবাহন চলাচলের এলাকা (ZTL)',
    'area pedonale': 'পথচারী এলাকা',
    'strada extraurbana principale': 'প্রধান উপশহরীয় হাইওয়ে',
    'strada extraurbana secondaria': 'দ্বিতীয় শ্রেণির উপশহরীয় হাইওয়ে',
    'strada urbana': 'শহরের ভেতরের রাস্তা',
    'corsia di emergenza': 'জরুরি লেন / ইমার্জেন্সি লেন',
    'corsia di marcia': 'স্বাভাবিক চলার লেন',
    'corsia di sorpasso': 'ওভারটেকিং লেন',
    'corsia di accelerazione': 'গতি বাড়ানোর লেন (প্রবেশ লেন)',
    'corsia di decelerazione': 'গতি কমানোর লেন (বাহির লেন)',
    'distanza di sicurezza': 'নিরাপদ দূরত্ব',
    'spazio di frenata': 'ব্রেক করার পর থামার দূরত্ব',
    'spazio di arresto': 'সম্পূর্ণ থামার মোট দূরত্ব',
    'tempo di reazione': 'প্রতিক্রিয়া সময়',
    'luci di posizione': 'পজিশন লাইট',
    'luci anabbaglianti': 'লো-বিম লাইট',
    'luci abbaglianti': 'হাই-বিম লাইট',
    'segnale luminoso': 'আলোক সংকেত / সিগন্যাল লাইট',
    'strisce longitudinali': 'লম্বালম্বি রোড লাইন',
    'strisce trasversali': 'আড়াআড়ি রোড লাইন',
    'strisce pedonali': 'জেব্রা ক্রসিং দাগ',
    'in caso di nebbia': 'কুয়াশার ক্ষেত্রে',
    'in caso di pioggia': 'বৃষ্টির ক্ষেত্রে',
    'in caso di neve': 'তুষারপাতের ক্ষেত্রে',

    // Single words
    'strada': 'রাস্তা / রোড',
    'carreggiata': 'মূল রাস্তা / ক্যারেজওয়ে',
    'corsia': 'লেন',
    'banchina': 'রাস্তার কিনারা / ব্যাংকিনা',
    'marciapiede': 'ফুটপাথ',
    'pedoni': 'পথচারী',
    'veicolo': 'যানবাহন / গাড়ি',
    'veicoli': 'যানবাহনগুলো / গাড়িগুলো',
    'conducente': 'চালক / ড্রাইভার',
    'velocità': 'গতি / স্পিড',
    'sosta': 'পার্কিং করা',
    'fermata': 'ক্ষণিকের থামা / স্টপ',
    'sorpasso': 'ওভারটেক করা',
    'vietato': 'নিষেধ / বেআইনি',
    'consentito': 'অনুমোদিত / বৈধ',
    'obbligo': 'বাধ্যতামূলক',
    'pericolo': 'বিপদ',
    'limite': 'সীমা / লিমিট',
    'sicurezza': 'নিরাপত্তা',
    'distanza': 'দূরত্ব',
    'incrocio': 'মোড় / চৌরাস্তা',
    'precedenza': 'অগ্রাধিকার / আগে যাওয়ার সুযোগ',
    'destra': 'ডানদিক',
    'sinistra': 'বামদিক',
    'freni': 'ব্রেকসমূহ',
    'pneumatici': 'টায়ারসমূহ',
    'motore': 'ইঞ্জিন',
    'luci': 'লাইটসমূহ',
    'nebbia': 'কুয়াশা',
    'ghiaccio': 'বরফ / তুষারপাত',
    'pioggia': 'বৃষ্টি',
    'autostrada': 'হাইওয়ে / এক্সপ্রেসওয়ে',
    'passaggio': 'ক্রসিং / পথ',
    'livello': 'লেভেল',
    'segnali': 'সংকেতসমূহ',
    'segnaletica': 'রোড সাইন / চিহ্ন',
    'continua': 'অবিচ্ছিন্ন / টানা',
    'discontinua': 'বিচ্ছিন্ন / ভাঙা',
    'doppio': 'দ্বিগুণ / উভয়',
    'senso': 'দিক / অভিমুখ',
    'unico': 'একমুখী',
    'arrestarsi': 'থামা',
    'guidare': 'ড্রাইভ করা / চালানো',
    'patente': 'ড্রriving লাইসেন্স',
    'cintura': 'বেল্ট / সিটবেল্ট',
    'casco': 'হেলমেট',
    'animali': 'পশু / জানোয়ার',
    'tenere': 'রাখা / বজায় রাখা',
    'vicino': 'কাছে / নিকটে',
    'margine': 'প্রান্ত / কিনারা',
    'destro': 'ডানদিক',
    'sinistro': 'বামদিক',
    'raffigurato': 'প্রদর্শিত / চিত্রে দেখানো',
    'preannuncia': 'পূর্বে সতর্ক করে / পূর্বাভাস দেয়',
  };

  static final List<McqQuestion> _allQuestions = [
    const McqQuestion(
      id: 1,
      chapter: 1,
      chapterName: 'Definizioni stradali',
      italian: 'La strada può comprendere le piste ciclabili',
      bangla: 'রাস্তার মধ্যে সাইকেল লেন অন্তর্ভুক্ত থাকতে পারে',
      isVero: true,
    ),
    const McqQuestion(
      id: 2,
      chapter: 1,
      chapterName: 'Definizioni stradali',
      italian: 'La carreggiata è destinata alla sosta di emergenza dei veicoli',
      bangla: 'ক্যারেজওয়ে শুধুমাত্র গাড়ির জরুরি পার্কিংয়ের জন্য নির্ধারিত',
      isVero: false,
    ),
    const McqQuestion(
      id: 3,
      chapter: 1,
      chapterName: 'Definizioni stradali',
      italian: 'La corsia può essere destinata ai veicoli che intendono svoltare',
      bangla: 'লেনটি বাঁক নিতে ইচ্ছুক যানবাহনের জন্য নির্ধারিত হতে পারে',
      isVero: true,
    ),
    const McqQuestion(
      id: 4,
      chapter: 1,
      chapterName: 'Definizioni stradali',
      italian: 'Il marciapiede è una parte della strada riservata ai pedoni',
      bangla: 'ফুটপাথ হলো রাস্তার একটি অংশ যা পথচারীদের জন্য সংরক্ষিত',
      isVero: true,
    ),
    const McqQuestion(
      id: 5,
      chapter: 1,
      chapterName: 'Definizioni stradali',
      italian: 'Sulle banchine è consentita la circolazione dei veicoli a motore',
      bangla: 'ব্যাংকিনা বা রাস্তার কিনারায় মোটরযান চলাচল অনুমোদিত',
      isVero: false,
    ),
    const McqQuestion(
      id: 6,
      chapter: 2,
      chapterName: 'Segnali di pericolo',
      italian: 'Il segnale di pericolo viene posto di norma a 150 metri dal pericolo',
      bangla: 'বিপদ সংকেতটি সাধারণত বিপদের স্থান থেকে ১৫০ মিটার পূর্বে স্থাপন করা হয়',
      isVero: true,
    ),
    const McqQuestion(
      id: 7,
      chapter: 2,
      chapterName: 'Segnali di pericolo',
      italian: 'In presenza del segnale STRADA SDRUCCIOLEVOLE occorre aumentare la velocità',
      bangla: 'পিচ্ছিল রাস্তার সংকেত থাকলে গতি বৃদ্ধি করা উচিত',
      isVero: false,
    ),
    const McqQuestion(
      id: 8,
      chapter: 2,
      chapterName: 'Segnali di pericolo',
      italian: 'In caso di pioggia lo spazio di frenata del veicolo aumenta',
      bangla: 'বৃষ্টির সময় গাড়ির ব্রেক করার পর থামার দূরত্ব বৃদ্ধি পায়',
      isVero: true,
    ),
    const McqQuestion(
      id: 9,
      chapter: 3,
      chapterName: 'Segnali di precedenza',
      italian: 'Il segnale DARE PRECEDENZA obbliga a fermarsi in ogni caso',
      bangla: 'অগ্রাধিকার দেওয়ার সংকেতটি সবক্ষেত্রেই সম্পূর্ণ থামতে বাধ্য করে',
      isVero: false,
    ),
    const McqQuestion(
      id: 10,
      chapter: 3,
      chapterName: 'Segnali di precedenza',
      italian: 'Il segnale STOP obbliga ad arrestarsi in corrispondenza della striscia trasversale di arresto',
      bangla: 'স্টপ সংকেতটি আড়াআড়ি স্টপ লাইনের সামনে থামতে বাধ্য করে',
      isVero: true,
    ),
    const McqQuestion(
      id: 11,
      chapter: 4,
      chapterName: 'Limiti di velocità',
      italian: 'Il limite massimo di velocità sulle autostrade è di norma 130 km/h',
      bangla: 'অটোস্ট্রাডায় সর্বোচ্চ স্বাভাবিক গতিসীমা হলো ১৩০ কিমি/ঘণ্টা',
      isVero: true,
    ),
    const McqQuestion(
      id: 12,
      chapter: 4,
      chapterName: 'Limiti di velocità',
      italian: 'Sulle strade extraurbane principali il limite di velocità è di 110 km/h',
      bangla: 'প্রধান অতিরিক্ত শহরতলির রাস্তায় গতিসীমা হলো ১১০ কিমি/ঘণ্টা',
      isVero: true,
    ),
    const McqQuestion(
      id: 13,
      chapter: 4,
      chapterName: 'Limiti di velocità',
      italian: 'Nei centri abitati il limite massimo di velocità è di norma 50 km/h',
      bangla: 'শহরাঞ্চলের ভেতরে স্বাভাবিক সর্বোচ্চ গতিসীমা হলো ৫০ কিমি/ঘণ্টা',
      isVero: true,
    ),
    const McqQuestion(
      id: 14,
      chapter: 5,
      chapterName: 'Distanza di sicurezza',
      italian: 'La distanza di sicurezza deve essere aumentata quando si viaggia ad alta velocità',
      bangla: 'উচ্চ গতিতে গাড়ি চালানোর সময় নিরাপদ দূরত্ব বাড়াতে হবে',
      isVero: true,
    ),
    const McqQuestion(
      id: 15,
      chapter: 5,
      chapterName: 'Distanza di sicurezza',
      italian: 'La distanza di sicurezza è indipendente dalle condizioni atmosferiche',
      bangla: 'নিরাপদ দূরত্ব আবহাওয়ার পরিস্থিতির ওপর নির্ভর করে না',
      isVero: false,
    ),
    const McqQuestion(
      id: 16,
      chapter: 6,
      chapterName: 'Norme sulla circolazione',
      italian: 'I veicoli senza motore devono percorrere la carreggiata il più vicino possibile al margine destro',
      bangla: 'ইঞ্জিনবিহীন যানবাহনগুলোকে রাস্তার একদম ডান প্রান্ত ঘেঁষে চলতে হবে',
      isVero: true,
    ),
    const McqQuestion(
      id: 17,
      chapter: 6,
      chapterName: 'Norme sulla circolazione',
      italian: 'È vietato il sorpasso sui dossi a carreggiata a doppio senso con due sole corsie',
      bangla: 'দুই লেনবিশিষ্ট উভয়মুখী রাস্তায় ঢালের ওপর ওভারটেক করা সম্পূর্ণ নিষেধ',
      isVero: true,
    ),
    const McqQuestion(
      id: 18,
      chapter: 6,
      chapterName: 'Norme sulla circolazione',
      italian: 'È consentito il sorpasso a destra di un tram che marcia al centro della strada',
      bangla: 'রাস্তার মাঝখান দিয়ে চলা ট্রামের ডান দিক দিয়ে ওভারটেক করা বৈধ যদি জায়গা থাকে',
      isVero: true,
    ),
    const McqQuestion(
      id: 19,
      chapter: 7,
      chapterName: 'Sosta e fermata',
      italian: 'La sosta è vietata in corrispondenza dei passaggi a livello',
      bangla: 'রেলওয়ে লেভেল ক্রসিংয়ে পার্কিং করা সম্পূর্ণ নিষিদ্ধ',
      isVero: true,
    ),
    const McqQuestion(
      id: 20,
      chapter: 7,
      chapterName: 'Sosta e fermata',
      italian: 'La fermata è consentita lungo le corsie di emergenza delle autostrade',
      bangla: 'অটোস্ট্রাডার জরুরি লেনে সাধারণ ক্ষণিকের জন্য থামা অনুমোদিত',
      isVero: false,
    ),
    const McqQuestion(
      id: 21,
      chapter: 8,
      chapterName: 'Luci e dispositivi',
      italian: 'Durante la guida è obbligatorio l\'uso dei fari anabbaglianti fuori dai centri abitati anche di giorno',
      bangla: 'দিনের বেলাতেও শহরাঞ্চলের বাইরে ড্রাইভ করার সময় লো-বিম লাইট ব্যবহার বাধ্যতামূলক',
      isVero: true,
    ),
    const McqQuestion(
      id: 22,
      chapter: 8,
      chapterName: 'Luci e dispositivi',
      italian: 'I proiettori di profondità (abbaglianti) si possono usare nei centri abitati sempre',
      bangla: 'শহরাঞ্চলের ভেতরে সবসময় হাই-বিম লাইট ব্যবহার করা যায়',
      isVero: false,
    ),
    const McqQuestion(
      id: 23,
      chapter: 9,
      chapterName: 'Dispositivi di sicurezza',
      italian: 'L\'uso delle cinture di sicurezza è obbligatorio per il conducente e per i passeggeri',
      bangla: 'চালক এবং যাত্রী উভয়ের জন্যই সিটবেল্ট পরা বাধ্যতামূলক',
      isVero: true,
    ),
    const McqQuestion(
      id: 24,
      chapter: 9,
      chapterName: 'Dispositivi di sicurezza',
      italian: 'Il casco protettivo è obbligatorio per i conducenti di tutti i motocicli',
      bangla: 'সকল মোটরসাইকেল চালকদের জন্য সুরক্ষামূলক হেলমেট পরা বাধ্যতামূলক',
      isVero: true,
    ),
    const McqQuestion(
      id: 25,
      chapter: 10,
      chapterName: 'Comportamenti in caso di incidente',
      italian: 'In caso di incidente stradale con feriti è obbligatorio prestare soccorso',
      bangla: 'আহত ব্যক্তিযুক্ত সড়ক দুর্ঘটনার ক্ষেত্রে সাহায্য প্রদান করা বাধ্যতামূলক',
      isVero: true,
    ),
    const McqQuestion(
      id: 26,
      chapter: 10,
      chapterName: 'Comportamenti in caso di incidente',
      italian: 'In caso di incidente con feriti occorre rimuovere immediatamente i feriti senza precauzioni',
      bangla: 'দুর্ঘটনায় আহত ব্যক্তিকে কোনো সতর্কতা ছাড়া অবিলম্বে টেনে বের করতে হবে',
      isVero: false,
    ),
    const McqQuestion(
      id: 27,
      chapter: 11,
      chapterName: 'Guida e stato psico-fisico',
      italian: 'L\'assunzione di alcol prima di guidare riduce il tempo di reazione',
      bangla: 'গাড়ি চালানোর আগে অ্যালকোহল গ্রহণ প্রতিক্রিয়া সময় কমিয়ে দেয় (দ্রুত প্রতিক্রিয়া করায়)',
      isVero: false,
    ),
    const McqQuestion(
      id: 28,
      chapter: 11,
      chapterName: 'Guida e stato psico-fisico',
      italian: 'Lo stato di ebbrezza può compromettere gravemente la capacità di concentrazione alla guida',
      bangla: 'মদ্যপ অবস্থা গাড়ি চালানোর সময় মনোযোগের ক্ষমতাকে মারাত্মকভাবে ব্যাহত করতে পারে',
      isVero: true,
    ),
    const McqQuestion(
      id: 29,
      chapter: 12,
      chapterName: 'Patente e documenti',
      italian: 'La patente di categoria B consente di guidare autovetture con massa fino a 3.500 kg',
      bangla: 'ক্যাটাগরি B লাইসেন্স দিয়ে ৩,৫০০ কেজি পর্যন্ত ভরের যাত্রীবাহী গাড়ি চালানো যায়',
      isVero: true,
    ),
    const McqQuestion(
      id: 30,
      chapter: 12,
      chapterName: 'Patente e documenti',
      italian: 'Durante la guida è obbligatorio avere con sé la patente di guida e la carta di circolazione',
      bangla: 'গাড়ি চালানোর সময় ড্রাইভিং লাইসেন্স এবং গাড়ির রেজিস্ট্রেশন কার্ড সঙ্গে রাখা বাধ্যতামূলক',
      isVero: true,
    ),
  ];

  static void initialize() {}

  static List<McqQuestion> getExamQuestions() {
    return List.from(_allQuestions);
  }

  static List<McqQuestion> getQuestionsForChapter(int chapterNum) {
    return _allQuestions.where((q) => q.chapter == chapterNum).toList();
  }
}
